# -*- coding: utf-8 -*-
"""generador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESyzrBEqUE68Ej3DgaOJ_KkkzZqWyjxG
"""

import streamlit as st
import pandas as pd
from fpdf import FPDF

# Título de la aplicación
st.title("Generador de Facturas y Cálculo de Impuestos")

# Formulario de entrada de datos
with st.form("invoice_form"):
    cliente = st.text_input("Nombre del Cliente")
    producto = st.text_input("Producto/Servicio")
    cantidad = st.number_input("Cantidad", min_value=1)
    precio_unitario = st.number_input("Precio Unitario", min_value=0.01)
    descuento = st.slider("Descuento (%)", 0, 100, 0)
    tasa_impuesto = st.selectbox("Seleccionar Impuesto", ["IVA 19%", "IVA 5%", "Sin Impuesto"])

    # Enviar el formulario
    submit_button = st.form_submit_button("Generar Factura")

# Cálculo del total y el impuesto
if submit_button:
    subtotal = cantidad * precio_unitario
    impuesto = 0
    if tasa_impuesto == "IVA 19%":
        impuesto = subtotal * 0.19
    elif tasa_impuesto == "IVA 5%":
        impuesto = subtotal * 0.05

    descuento_total = subtotal * (descuento / 100)
    total = subtotal + impuesto - descuento_total

    # Mostrar resultados
    st.subheader("Factura Generada")
    st.write(f"Cliente: {cliente}")
    st.write(f"Producto/Servicio: {producto}")
    st.write(f"Cantidad: {cantidad}")
    st.write(f"Precio Unitario: {precio_unitario}")
    st.write(f"Descuento: {descuento}%")
    st.write(f"Subtotal: {subtotal}")
    st.write(f"Impuesto: {impuesto}")
    st.write(f"Total: {total}")

    # Generar PDF
    if st.button("Descargar Factura en PDF"):
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=12)
        pdf.cell(200, 10, txt="Factura Generada", ln=True, align='C')
        pdf.cell(200, 10, txt=f"Cliente: {cliente}", ln=True)
        pdf.cell(200, 10, txt=f"Producto/Servicio: {producto}", ln=True)
        pdf.cell(200, 10, txt=f"Cantidad: {cantidad}", ln=True)
        pdf.cell(200, 10, txt=f"Precio Unitario: {precio_unitario}", ln=True)
        pdf.cell(200, 10, txt=f"Subtotal: {subtotal}", ln=True)
        pdf.cell(200, 10, txt=f"Impuesto: {impuesto}", ln=True)
        pdf.cell(200, 10, txt=f"Total: {total}", ln=True)

        # Guardar el archivo PDF
        pdf.output("/tmp/factura.pdf")
        st.download_button("Descargar PDF", data=open("/tmp/factura.pdf", "rb").read(), file_name="factura.pdf")